config/routes.rb
Rails.application.routes.draw do

  root              'static_pages#home'
  get 'help' =>     'static_pages#help'
  get 'about' =>    'static_pages#about'
  get 'contact' =>  'static_pages#contact'
  get 'signup' =>   'users#new'
  get 'login' =>    'sessions#new'
  post 'login' =>   'sessions#create'
  delete 'logout' =>'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end
  
  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  The <%=link_to "Sample App", root_path %> is the application for simple people. It is developed in
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
</p>

<img id="kot", src="http://niespodzianka.pl/presents/8f6e3a5e5ccae274461531f2bd2120d9.jpg"/>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Cotact me at <%= mail_to "marek.parafianowicz@gmail.com" %> or at <a href="https://www.facebook.com/marek.parafianowicz">Facebook</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

<h1>Help</h1>
<p>
  Get help on the Sample App at the <%= mail_to "marek.parafianowicz@gmail.com" %>.
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to the Sample App</h1>

    <h2>This is the home page for simple people... Deal with it.</h2>
    <h2>But, for real, it will be better than Twitter!</h2>
  
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>
<!--<%= link_to image_tag("rails.png", alt: "Rails logo"), 'http://rubyonrails.org/' %>-->